name: circle_flags
description: A collection of roundd flags
version: 1.1.0
repository: https://github.com/cedvdb/flutter_circle_flags

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=3.7.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/svg/
